### ISSUE TITLE
setting BANDB_DBPATH does not work as expected

### ISSUE THREAD

**Issue by Lassulus** [solanum-ircd/solanum#156]
on nixos/nixpkgs it was not possible to start solanum with the package (https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/irc/solanum/default.nix).
it failed with the error:
```
May 18 19:26:23 coaxmetal solanum[11242]:   notice: now running in foreground mode from /nix/store/ayyz3mjnaqqr37cz7a2bf7z3grj3yrq1-solanum-unstable-2020-12-14 as pid 11242 ...
May 18 19:26:23 coaxmetal solanum[11242]: bandb - bandb failure: Unable to open sqlite database: unable to open database file
May 18 19:26:23 coaxmetal systemd[1]: solanum.service: Main process exited, code=exited, status=1/FAILURE
May 18 19:26:23 coaxmetal systemd[1]: solanum.service: Failed with result 'exit-code'.
```

with this patch it worked as expected:
```
diff --git a/ircd/bandbi.c b/ircd/bandbi.c
index 29a3bfa2..16a40f17 100644
--- a/ircd/bandbi.c
+++ b/ircd/bandbi.c
@@ -83,7 +83,6 @@ start_bandb(void)
 	const char *suffix = "";
 #endif
 
-	rb_setenv("BANDB_DBPATH", ircd_paths[IRCD_PATH_BANDB], 1);
 	if(bandb_path == NULL)
 	{
 		snprintf(fullpath, sizeof(fullpath), "%s%cbandb%s", ircd_paths[IRCD_PATH_LIBEXEC], RB_PATH_SEPARATOR, suffix);
```

So it seems setting `BANDB_DBPATH` actually has no effect right now

**Comment by dwfreed** [comment]
As far as I can tell, the only way that line would have any real effect is if you're running under Windows; are you?

**Comment by Lassulus** [comment]
no, I'm on NixOS, a linux distribution. the patch actually removes the line.

**Comment by dwfreed** [comment]
I understand the patch is removing the line; the line only does something truly meaningful on Windows, otherwise it sets the same value that bandb would be using if it wasn't set:

https://github.com/solanum-ircd/solanum/blob/a07fd84069d95fdd7adc79b4d169b8ed58069dfa/include/defaults.h#L118
https://github.com/solanum-ircd/solanum/blob/a07fd84069d95fdd7adc79b4d169b8ed58069dfa/ircd/ircd.c#L134
https://github.com/solanum-ircd/solanum/blob/a07fd84069d95fdd7adc79b4d169b8ed58069dfa/bandb/rsdb_sqlite3.c#L65-L70

Only on Windows, `relocate_paths` is called right at ircd startup, which changes the bandb path to be relative to the ircd binary.

The only other theory I have is you've somehow ended up with a bandb built with a different DBPATH than solanum; I'd be interested to see the environment variable value (bandb looks like it will remain running after it fails, so you can poke its /proc/pid/environ file for the value), as well as what DBPATH is set to in bandb and solanum (can get this with `strings bandb | fgrep '/ban.db'`)

**Comment by Lassulus** [comment]
hmm, I cannot reproduce it anymore. Not sure why this happened.
I'm pretty sure removing the line fixed a startup issue for me, but maybe it was unrelated noise.

**Comment by dwfreed** [comment]
Your startup issue was probably that the directory pointed to by DBPATH (which, based on nix's options, would be /var/lib/solanum) didn't exist.
