### ISSUE TITLE
Connection setup delayed by seconds

### ISSUE THREAD

**Issue by michaelortmann** [solanum-ircd/solanum#442]
solanum idles for up to 1 second when there is work to do available.

during sasl auth this happens more than 1 time, effectively delaying every connection setup by 2 seconds or more than necessary.

```
$ strace -tt ~/opt/solanum/bin/solanum -foreground
[...]
07:18:20.694950 recvfrom(227, "AUTHENTICATE aWYgeW91IHJlYWQgdGhpcyB5b3UgaGFja2VkIHRoZSBzb2xhbnVtIGlzc3VlIDsp\r\n", 16384, 0, NULL, NULL) = 79
07:18:20.695032 epoll_wait(3, [{events=EPOLLIN, data={u32=163264, u64=88785564106176}}], 1024, -1) = 1
07:18:20.702860 read(254, "\1\0\0\0\0\0\0\0", 8) = 8
07:18:20.702910 epoll_wait(3, [{events=EPOLLIN, data={u32=103936, u64=88785564046848}}], 1024, -1) = 1
07:18:21.630601 read(118, "\1\0\0\0\0\0\0\0", 8) = 8
[...]
```

**Comment by dwfreed** [comment]
This is expected behavior.  Flood ratelimits apply to "unknown" clients (those that haven't finished connection registration) too; the limit applied is a burst of whatever client_flood_burst_max is set to (default 5, generally shouldn't be changed), and then 1 message per second. The 5 message burst will get used by `CAP LS`, `CAP REQ sasl`, `NICK foo`, `USER foo * * :bar`, and `AUTHENTICATE PLAIN`, and then the `AUTHENTICATE accountpasswordbase64` will be the first that has to wait a second. On any non-trivial network, waiting for the `AUTHENTICATE +` from services takes a substantial fraction of a second, so one doesn't really notice.

**Comment by michaelortmann** [comment]
thank you for the instant great answer! :)
